### ISSUE TITLE
TODO goal: working version 1

### ISSUE THREAD

**Issue by aw** [aw/fiveforths#1]
This **TODO**'s goal is to aim for an initial working version 1 which can be flash to a Longan Nano MCU. The list is unsorted and a work in progress (i.e: more items can/will be added as needed).

- [x] Validate location of constants in Flash memory
- [x] Validate location of variables in RAM
- [x] Validate memory locations of stacks (and their size -- 256 Bytes each)
- [x] Test program loading and register values in _Ripes_ and _GDB_
- [x] Add `SOS` register and use it as the second top of stack item instead of `DSP`
- [x] Verify existing primitives for proper use of `TOS` and `SOS` registers
- [x] Implement missing primitives:
  - [x] `:`
  - [x] `;`
  - [x] `>in`
  - [x] `key`
  - [x] `emit`
- [x] Implement interpreter loop
- [x] Implement terminal input buffer functions (UART)
- [x] Implement lookup function to find a word in the dictionary
- [x] Implement `compile` and `execute` functions

**Comment by aw** [comment]
Done!

There's a few minor things I want to cleanup and implement, but for the moment this can be considered 100% fully functional. Yay!
